version: '3'
services:
  bi-ui:
    image: "bi-ui:latest"
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - business-index-api
    environment:
      - NODE_ENV=development
      - SERVER_AUTH_URL=http://localhost:3002/auth
      - SERVER_API_GW_URL=http://localhost:3002
      - BI_UI_TEST_ADMIN_USERNAME=admin
      - BI_UI_TEST_ADMIN_PASSWORD=admin
      - BI_UI_TEST_USER_USERNAME=test
      - BI_UI_TEST_USER_PASSWORD=test
      - REACT_APP_ENV=local
      - API_URL=http://business-index-api:9000
      - REACT_APP_AUTH_URL=http://localhost:3001
      - REACT_APP_API_URL=http://localhost:3001/api
  business-index-api:
    image: "ons-business-index-api:1.0"
    ports:
     - "9000:9000"
    environment:
     - APPLICATION_SECRET=wF^UCO:x2eg/^Hd>Y7[@Ki/=MnPW5@eCSk;9oAAfe4xN2DEoy2zXEVj>RIgOmyDN
     - environment=default
     - ONS_BI_API_ES_URI=elasticsearch://elasticsearch:9300
     - ONS_BI_API_ES_CLUSTER_NAME=elasticsearch
     - ONS_BI_API_IMPORT_SAMPLE=true
    depends_on:
      - elasticsearch
  elasticsearch:
    image: "elasticsearch:2.4"
    ports:
     - "9300:9300"
     - "9200:9200"
    environment:
     - discovery.type=single-node